export default {
    'GET_RECIPES': 'GET_RECIPES',
    'GET_RECIPES_SUCCESS': 'GET_RECIPES_SUCCESS',
    'GET_RECIPES_ERROR': 'GET_RECIPES_ERROR',

    'GET_RECIPESID' : 'GET_RECIPESID',
    'GET_RECIPESID_SUCCESS' : 'GET_RECIPESID_SUCCESS',
    'GET_RECIPESID_ERROR' : 'GET_RECIPESID_ERROR',

    'GET_CHEFS' : 'GET_CHEFS',
    'GET_CHEFS_SUCCESS' : 'GET_CHEFS_SUCCESS',
    'GET_CHEFS_ERROR' : 'GET_CHEFS_ERROR',
    
    'GET_INGREDIENTS' : 'GET_INGREDIENTS',
    'GET_INGREDIENTS_SUCCESS' : 'GET_INGREDIENTS_SUCCESS',
    'GET_INGREDIENTS_ERROR' : 'GET_INGREDIENTS_ERROR',

    'GET_INGREDIENTSID' : 'GET_INGREDIENTSID',
    'GET_INGREDIENTSID_SUCCESS' : 'GET_INGREDIENTSID_SUCCESS',
    'GET_INGREDIENTSID_ERROR' : 'GET_INGREDIENTSID_ERROR',
    

    'GET_GALLERIES' : 'GET_GALLERIES',
    'GET_GALLERIES_SUCCESS' : 'GET_GALLERIES_SUCCESS',
    'GET_GALLERIES_ERROR' : 'GET_GALLERIES_ERROR',

  }